### ISSUE TITLE
Question: What class are the pasted anomalies considered as?

### ISSUE THREAD

**Issue by mbisan** [matejgrcic/DenseHybrid#4]
In [line 115 of the train function](https://github.com/matejgrcic/DenseHybrid/blob/main/experiments/semseg_negatives_joint_th.py) the labels with anomalies marked as `self.args.num_classes + 1` is marked on those positions as `self.args.num_classes`. For the cityscapes dataset this would mean setting the class at the pasted positions to 19, which is class `unlabeled`, or rather the class ignored when computing the cost.

Is this right?

**Comment by matejgrcic** [comment]
The classification loss is not computed in the pasted negative object. We implement this by assigning ignore label to the corresponding pixel.

**Comment by mbisan** [comment]
Ok, thank you for confirming this.
