### ISSUE TITLE
The checkpoint for SMIYC test

### ISSUE THREAD

**Issue by yyliu01** [matejgrcic/DenseHybrid#5]
Hi Matej,

Could I ask for the checkpoint in SMIYC dataset?

Cheers,
Yuyuan

**Comment by matejgrcic** [comment]
Hi,

I've just updated the README page. You can find the weights there.

Matej

**Comment by yyliu01** [comment]
Hi Matej,

Thanks for your checkpoint! @matejgrcic 

The evaluation results based on your checkpoint are in below:

SMIYC-RoadAnomalyTrack:
AUROC score for segment_me_anomaly: **0.8927** 
AUPRC score for segment_me_anomaly: **0.6362** 
FPR@TPR95 for segment_me_anomaly: **0.5071** 

SMIYC-ObstacleTrack:
AUROC score for segment_me_obstacle: 0.9984 
AUPRC score for segment_me_obstacle: 0.8769 
FPR@TPR95 for segment_me_obstacle: 0.0058 

The results seem far away from the test results in your paper.

Please note: I've utilised the measurement for anomaly objects based on the code from [here](https://github.com/matejgrcic/DenseHybrid/blob/c03555d311f4eb9dfa755b2be4c6af17aa34c41a/evaluations/evaluations.py#L10). 

Is there anything I'm missing?

Cheers,
Yuyuan

**Comment by matejgrcic** [comment]
That's strange.
Did you evaluate using the official code: https://github.com/SegmentMeIfYouCan/road-anomaly-benchmark
I've uploaded my script for submission if it helps.

I get:
AP AnomalyTrack val: 86.5%
AP ObstacleTrack val: 94.8%

**Comment by yyliu01** [comment]
Hi Matej,

I've found the difference and figure it out. 
Thanks for your time.

Cheers,
Yuyuan

**Comment by yyliu01** [comment]
For anyone who may have this concerns, the differences are in mean and std of the image, as shown below:

C.image_mean = numpy.array([0, 0, 0])  
C.image_std = numpy.array([1, 1, 1])
